version: '3.8'

services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  backend:
    build: ./backend
    ports: 
      - 4000:4000
    command: npm start
    depends_on:
      - postgres
  frontend: 
    build: ./frontend/app
    ports:
      - 8888:80
    depends_on:
      - backend
volumes:
  postgres: