version: '3.1'

services:

  backend:
    build: ./backend
    ports: 
      - 4000:4000
    command: npm start 
    
  frontend: 
    build: ./frontend/app
    ports:
      - 8888:80
    depends_on:
      - backend