version: '3.1'

services:

  backend:
    build: ./backend
    ports: 
      - 4000:4000
    command: npm start

  frontend: 
    build: ./frontend/app
    ports:
      - 3333:3000
    command: npm start
    depends_on:
      - backend